#!/bin/bash

while sleep 1; do
  systemctl is-active --quiet hostapd && echo "default-on" > /sys/class/leds/LED2/trigger || echo "none" > /sys/class/leds/LED2/trigger
  sleep 1
  systemctl is-active --quiet openvpn@server && echo "default-on" > /sys/class/leds/LED3/trigger || echo "none" > /sys/class/leds/LED3/trigger
done
