#!/bin/bash
## A simple command for Debian that will change the WPA Key in hostapd
## usage:
## sudo ./pskc

new_ssid=$2
new_psk=$3

wifidev="wlan0"

if [ "$1" = "enable" ]; then
	
	systemctl enable hostapd
	systemctl start hostapd

	echo "... Hotspot Aktiviert"

elif [ "$1" = "disable" ]; then

	systemctl stop hostapd
	systemctl disable hostapd
	
	echo "... Hotspot Deaktiviert"

elif [ "$1" = "change" ]; then

	echo
	echo "[ KEY: $new_ssid ]"
	echo "[ KEY: $new_psk ]"
	echo

    sudo sed -i "s/ssid=.*/ssid="$new_ssid"/" /etc/hostapd.conf
    sudo sed -i "s/wpa_passphrase=.*/wpa_passphrase="$new_psk"/" /etc/hostapd.conf
	
	echo "... Hotspot restart"
	systemctl enable hostapd
	systemctl restart hostapd

else
    echo "-------------------------"
    echo "Keine Parameter definiert"
    echo "Usage: pskc 'PSK'"
    echo "-------------------------"
fi
