#!/bin/bash
## A simple command for Debian that will send UPnP for OpenVPN Service
## usage:
## ./upnps

ip="$(ip a | grep 'eth0' | egrep 'inet' | grep -v 169.254 | awk '{ print $2 }' | cut -f1 -d'/')"
upnpc -a "$ip" 1194 1194 UDP